version: '3.0'
services: 
  backend:
    image: node-just-sketch
    container_name: node-just-sketch
    restart: always
    build: ./
    ports: 
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - ./error.log:/usr/src/app/error.log
    env_file: 
      - .env
    links: 
      - redis
    environment:
      - REDIS_URL=$REDIS_URL
      - MONGODB_URL_DEVELOPMENT=$MONGODB_URL_DEVELOPMENT
      - MONGODB_URL_PRODUCTION=$MONGODB_URL_PRODUCTION
      - NODE_ENV=$NODE_ENV
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes: 
      - ./redis-data:/var/lib/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf