version: '3.8'
services: 
  backend:
    container_name: node-sketch-it
    restart: always
    build: ./
    ports: 
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - ./error.log:/usr/src/app/error.log
    links: 
      - mongo
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGODB_URL=mongodb://mongo:27017/sketch_it
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports: 
      - "27018:27017"
    volumes:
      - ./data:/data/db
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes: 
      - ./redis-data:/var/lib/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf