version: '3.8'
services: 
  backend:
    container_name: node-sketch-it
    restart: always
    build: ./
    ports: 
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - ./error.log:/usr/src/app/error.log
    links: 
      - redis
    environment:
      - REDIS_URL=$REDIS_URL
      - MONGODB_URL_DEVELOPMENT=$MONGODB_URL_DEVELOPMENT
      - MONGODB_URL_PRODUCTION=$MONGODB_URL_PRODUCTION
      - NODE_ENV=$NODE_ENV
    networks:
      - app-network
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes: 
      - ./redis-data:/var/lib/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/justsketch
      - dhparam:/etc/ssl/certs
    depends_on:
      - backend
    networks:
      - app-network
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/justsketch
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/justsketch --email $EMAIL --agree-tos --no-eff-email --force-renewal -d $DOMAIN_NAME
volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: $ROOT_PATH
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: $CERT_PATH
      o: bind

networks:
  app-network:
    driver: bridge