version: '3.0'
services: 
  backend:
    image: justsketch.azurecr.io/node-just-sketch:v1
    container_name: node-just-sketch
    domainname: "justsketch"
    restart: on-failure
    build: ./
    ports: 
      - "3000:3000"
    env_file: 
      - .env
    links: 
      - redis
    environment:
      - REDIS_URL=$REDIS_URL
      - MONGODB_URL_DEVELOPMENT=$MONGODB_URL_DEVELOPMENT
      - MONGODB_URL_PRODUCTION=$MONGODB_URL_PRODUCTION
      - NODE_ENV=$NODE_ENV
    command: ["npm", "start"]
  redis:
    container_name: redis
    image: redis:latest
    restart: on-failure
    networks:
      - default
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes: 
      - redis-data:/var/lib/redis
volumes:
    redis-data:
      driver: azure_file
      driver_opts:
          share_name: $SHARE_NAME
          storage_account_name: $STORAGE_ACCOUNT_NAME


