version: '3.8'
services: 
  justsketchbackend:
    container_name: justsketchbackend
    restart: always
    build: ./
    command: npm run dev
    ports: 
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - ./error.log:/usr/src/app/error.log
    links: 
      - redis
    environment:
      - REDIS_URL=$REDIS_URL
      - MONGODB_URL_DEVELOPMENT=$MONGODB_URL_DEVELOPMENT
      - MONGODB_URL_PRODUCTION=$MONGODB_URL_PRODUCTION
      - NODE_ENV=$NODE_ENV
    networks:
      - app-network
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes: 
      - ./redis-data:/var/lib/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - app-network
networks:
  app-network:
    driver: bridge